#!/usr/bin/env python3
"""
CB-Remix-scripts/update_config_yml.py

Patches specific fields in a Jekyll _config.yml from the "config"
spreadsheet tab, without disturbing comments or unrelated keys.

Self-contained: the function below imports everything it needs internally,
so this whole file can be copy-pasted on its own into a new
conversation/file if you just want to iterate on this piece.

Does NOT talk to the network or Google Sheets — it only operates on a
DataFrame handed to it (config_df) plus a path to an existing _config.yml.

Dependencies (install once):
    pip install pandas ruamel.yaml

Usage (as a library, not run directly):
    from update_config_yml import update_config_yml
"""


def update_config_yml(
    yaml_path,
    config_df,
    category_col: str = "category",
    content_col: str = "content",
) -> None:
    """Patch fields in a Jekyll _config.yml from the "config" spreadsheet tab.

    Self-contained: everything needed (the field map, the path-setter, the
    imports it uses) lives inside this function, so it can be copy-pasted
    on its own into a new conversation/file. Only needs `pandas` (as `pd`
    somewhere importable) and `ruamel.yaml` installed in the environment.

    Driven entirely by FIELD_MAP below: for each (yaml_path, category) pair,
    look up *category* in the spreadsheet and, if a non-blank value is
    found, write it to *yaml_path* in the yaml file.

    - Paths under "site_languages" are created if missing (that block is
      meant to be generated by this script).
    - All other paths must already exist in _config.yml, or the write is
      skipped and reported — this avoids silently inventing new top-level
      keys with no surrounding comment/context.
    - A blank cell in the spreadsheet is skipped rather than clearing an
      existing value.

    Some values also drive OTHER fields derived from them rather than
    copied verbatim — see DERIVED_MAP below. Currently this covers
    "lang2-id": that spreadsheet value doesn't just get written into
    site_languages[1].lang_id, it also determines the folder/permalink/lang
    for language 2's pages in the "defaults" block, e.g.:

        defaults:
        - scope:
            path: 'pt'          # <- lang2-id
          values:
            permalink: /pt/:basename   # <- template built from lang2-id
            lang: 'pt'          # <- lang2-id

    If lang2-id changes (e.g. Portuguese -> Spanish, "pt" -> "es"), this
    block needs to change too, or Jekyll keeps looking for pages under the
    old language folder and serving them at the old permalink even though
    site_languages now says the site is in the new language.

    Uses ruamel.yaml (round-trip mode) instead of PyYAML specifically
    because it preserves comments and key ordering, which a plain
    yaml.safe_load/yaml.dump cycle would otherwise strip out.
    """
    import re
    import pandas as pd
    from ruamel.yaml import YAML

    # ── yaml_path -> spreadsheet category ───────────────────────────────
    # One line per field. Left side is where it lives in _config.yml (dot
    # path, with [N] for a position inside a list). Right side is the
    # "category" value to look for in the spreadsheet's "config" tab.
    # To wire up a new field, just add a line here.
    FIELD_MAP = {
        "url":                                      "url",
        "baseurl":                                  "baseurl",
        "source-code":                              "source-code",

        # lang1 (English) is the site's default language, so it uses the
        # plain top-level fields directly.
        "title":                                    "title-lang1",
        "tagline":                                  "tagline-lang1",
        "description":                              "description-lang1",

        # site_languages[0] = lang1 (English), site_languages[1] = lang2 (Portuguese)
        "site_languages[0].lang_id":                "lang1-id",
        "site_languages[0].lang_display":           "lang1",
        "site_languages[1].lang_id":                "lang2-id",
        "site_languages[1].lang_display":           "lang2",
        "site_languages[1].lang_site_title":        "title-lang2",
        "site_languages[1].lang_site_tagline":      "tagline-lang2",
        "site_languages[1].lang_site_description":  "description-lang2",
    }

    # ── category -> other yaml_paths driven by that same value ─────────
    # Each entry is a list of (yaml_path, transform) pairs. `transform`
    # takes the raw spreadsheet value and returns what should actually be
    # written at that path (identity for a straight copy, or a small
    # template for something like the permalink).
    #
    # These paths must already exist in _config.yml (create_missing=False)
    # — this only ever *updates* the language-2 defaults entry, it doesn't
    # create one from scratch, since the "pages" defaults entry after it
    # also needs to exist and their relative order/shape matters.
    DERIVED_MAP = {
        "lang2-id": [
            ("defaults[0].scope.path",   lambda v: v),
            ("defaults[0].values.lang",  lambda v: v),
            ("defaults[0].values.permalink", lambda v: f"/{v}/:basename"),
        ],
    }

    path_segment_re = re.compile(r"^([\w-]+)(?:\[(\d+)\])?$")

    def set_yaml_path(config_data, path: str, value, create_missing: bool = False) -> bool:
        """Set a value at a dot/bracket path like "site_languages[1].lang_display".

        If *create_missing* is False, the path must already exist (aside
        from the final key) or nothing is changed and False is returned.
        If True, missing dicts/list slots are created along the way.
        """
        segments = path.split(".")
        node = config_data

        for i, segment in enumerate(segments):
            match = path_segment_re.match(segment)
            key, index = match.group(1), match.group(2)
            is_last = i == len(segments) - 1

            if index is None:
                if is_last:
                    if key not in node and not create_missing:
                        return False
                    node[key] = value
                    return True
                if key not in node or node[key] is None:
                    if not create_missing:
                        return False
                    node[key] = {}
                node = node[key]
            else:
                index = int(index)
                if key not in node or node[key] is None:
                    if not create_missing:
                        return False
                    node[key] = []
                item_list = node[key]
                while len(item_list) <= index:
                    if not create_missing:
                        return False
                    item_list.append({})
                if is_last:
                    item_list[index] = value
                    return True
                node = item_list[index]

        return False

    if not yaml_path.exists():
        print(f"[WARN] {yaml_path} does not exist — skipping config update")
        return

    if category_col not in config_df.columns or content_col not in config_df.columns:
        print(
            f"[WARN] config sheet is missing '{category_col}' or '{content_col}' "
            f"column(s) — skipping config update. Found columns: {list(config_df.columns)}"
        )
        return

    # category -> cleaned value, straight from the spreadsheet
    values_by_category = {
        str(row[category_col]).strip(): (
            "" if pd.isna(row[content_col]) else str(row[content_col]).strip()
        )
        for _, row in config_df.iterrows()
    }

    yaml = YAML()
    yaml.preserve_quotes = True

    with open(yaml_path, "r", encoding="utf-8") as fh:
        config_data = yaml.load(fh)

    updated, skipped_missing, skipped_blank = [], [], []

    for yaml_field_path, category in FIELD_MAP.items():
        if category not in values_by_category:
            continue  # this category isn't in the spreadsheet at all

        value = values_by_category[category]
        if value == "":
            skipped_blank.append(yaml_field_path)
            continue

        create_missing = yaml_field_path.startswith("site_languages")
        if set_yaml_path(config_data, yaml_field_path, value, create_missing=create_missing):
            updated.append(yaml_field_path)
        else:
            skipped_missing.append(yaml_field_path)

    for category, derived_targets in DERIVED_MAP.items():
        if category not in values_by_category:
            continue

        value = values_by_category[category]
        if value == "":
            skipped_blank.extend(path for path, _ in derived_targets)
            continue

        for yaml_field_path, transform in derived_targets:
            derived_value = transform(value)
            if set_yaml_path(config_data, yaml_field_path, derived_value, create_missing=False):
                updated.append(yaml_field_path)
            else:
                skipped_missing.append(yaml_field_path)

    with open(yaml_path, "w", encoding="utf-8") as fh:
        yaml.dump(config_data, fh)

    print(f"[DONE] {yaml_path} updated. Fields set: {updated}")
    if skipped_missing:
        print(
            f"[WARN] These yaml paths don't exist in {yaml_path} (and aren't "
            f"auto-created), so they were skipped: {skipped_missing}"
        )
    if skipped_blank:
        print(f"[INFO] These fields were blank in the spreadsheet, so left untouched: {skipped_blank}")